language: python

python:
  - '2.7'

install:
  - pip install Pillow
  - pip install coveralls

script:
  - python tests/tester.py
  - coverage run --source=logobot,logo,progressbar tests/tester.py test

after_success: coveralls